### ISSUE TITLE
Not loading at all

### ISSUE THREAD

**Issue by kriimakt** [AUTOMATIC1111/stable-diffusion-webui-tensorrt#12]
I'm getting the following error :
Error loading script: trt.py
Traceback (most recent call last):
  File "D:\UNSTABLE2\stable-diffusion-webui\modules\scripts.py", line 263, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "D:\UNSTABLE2\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\UNSTABLE2\stable-diffusion-webui\extensions\stable-diffusion-webui-tensorrt\scripts\trt.py", line 6, in <module>
    from modules import script_callbacks, sd_unet, devices, shared, paths_internal
ImportError: cannot import name 'sd_unet' from 'modules' (unknown location)

I followed the installation instructions but... The extension doesn't load :(

**Comment by Adolfiux** [comment]
Same here, I followed solution #7, but nothing changed.

**Comment by TigerFox57** [comment]
Me too, as they say, although solution #7 fixed the majority of the errors I was getting, so it's just this ImportError thing that's the hold up.

UPDATE: Did git checkout dev and this got past the error, so now I'm waiting for the conversion to finish, assuming it actually does.

**Comment by MxDeWitt** [comment]
@TigerFox57, have the same issue, and I'm probably doing something wrong since `git checkout dev` gives me the following:
`error: pathspec 'dev' did not match any file(s) known to git`
Checking available branches yields this:

``` 
  master                5e5352c Merge pull request #4 from szhublox/linux-ld
  remotes/origin/HEAD   -> origin/master
  remotes/origin/master 5e5352c Merge pull request #4 from szhublox/linux-ld
```

**Comment by TigerFox57** [comment]
> @TigerFox57, have the same issue, and I'm probably doing something wrong since `git checkout dev` gives me the following: `error: pathspec 'dev' did not match any file(s) known to git` Checking available branches yields this:
> 
> ```
>   master                5e5352c Merge pull request #4 from szhublox/linux-ld
>   remotes/origin/HEAD   -> origin/master
>   remotes/origin/master 5e5352c Merge pull request #4 from szhublox/linux-ld
> ```

My knowledge of git is practically non existant I'm afraid, so I can't really shed any light on your problem. When I do 

git branch --list

I get `* dev
  master`

I can however report that on my laptop with a mobile RTX 3080 Ti, generating 512 x 512 images goes from  about 9 it/sec to about 15 it/sec. using 20 steps Euler_a. Not sure about image quality though, the console reported a lot of stuff during conversion that seemed to say that things could be tweaked a bit.

**Comment by drphero** [comment]
You have to run `git checkout dev` in the stable-diffusion-webui directory, but you might want to run `git pull` first.
