### ISSUE TITLE
Error loading script: trt.py

### ISSUE THREAD

**Issue by sunwukong0727** [AUTOMATIC1111/stable-diffusion-webui-tensorrt#16]
script_module = script_loading.load_module(scriptfile.path)
  File "H:\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "H:\stable-diffusion-webui\extensions\stable-diffusion-webui-tensorrt\scripts\trt.py", line 6, in <module>
    from modules import script_callbacks, sd_unet, devices, shared, paths_internal
ImportError: cannot import name 'sd_unet' from 'modules' (unknown location)

**Comment by jepjoo** [comment]
**edit: found the problem: apparently need to use "dev" branch**

I'm having a similar problem.

I installed 2019 c++ build tools and pycuda & onnx after which they both seem to have installed fine and errors related to those are gone. Now I get this:

Error loading script: trt.py
Traceback (most recent call last):
  File "C:\Auto1111\modules\scripts.py", line 263, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "C:\Auto1111\modules\script_loading.py", line 10, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Auto1111\extensions\stable-diffusion-webui-tensorrt\scripts\trt.py", line 6, in <module>
    from modules import script_callbacks, sd_unet, devices, shared, paths_internal
ImportError: cannot import name 'sd_unet' from 'modules' (unknown location)

**Comment by sunwukong0727** [comment]
git checkout dev                 感谢jilekjosef

**Comment by MxDeWitt** [comment]
@sunwukong0727 @jepjoo `dev` branch seems to be invisible for me both in web and in Git bash when I call `$ git branch -r --list` from the directory of the extension. Is it visible/accessible for everyone else? How does that work?

**Comment by sunwukong0727** [comment]
在stable  diffution 主目录下   鼠标右键
 git checkout dev

**Comment by zaazii** [comment]
Excuse my noobness but how can I get the "dev" branch? Or what should I do before I type "git checkout dev"?

**Comment by TigerFox57** [comment]
> @sunwukong0727 @jepjoo `dev` branch seems to be invisible for me both in web and in Git bash when I call `$ git branch -r --list` from the directory of the extension. Is it visible/accessible for everyone else? How does that work?

I think you have to do git checkout dev from the directory of the main repo, not the extension.

**Comment by sunwukong0727** [comment]
Find a blank space in the main directory of stable diffusion, right-click
on git base, and enter git checkout dev

**Comment by zaazii** [comment]
Thank you. It said branch is up to date with origin\dev. But I am still getting the Error loading script: trt.py

**Comment by SephVT** [comment]
> Thank you. It said branch is up to date with origin\dev. But I am still getting the Error loading script: trt.py

I am also getting the same error despite being on dev.

> No module 'xformers'. Proceeding without it.
Error loading script: trt.py
Traceback (most recent call last):
  File "E:\StableDiffusion\web-ui\modules\scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "E:\StableDiffusion\web-ui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\StableDiffusion\web-ui\extensions\stable-diffusion-webui-tensorrt\scripts\trt.py", line 6, in <module>
    from modules import script_callbacks, sd_unet, devices, shared, paths_internal
ImportError: cannot import name 'sd_unet' from 'modules' (unknown location)

Despite being on dev branch:
> PS E:\StableDiffusion\web-ui> git checkout dev
Already on 'dev'
Your branch is up to date with 'origin/dev'

**Comment by Xility-Wil** [comment]
> Thank you. It said branch is up to date with origin\dev. But I am still getting the Error loading script: trt.py

I am also getting the same error despite being on dev.

> No module 'xformers'. Proceeding without it.
Error loading script: trt.py
Traceback (most recent call last):
  File "E:\StableDiffusion\web-ui\modules\scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "E:\StableDiffusion\web-ui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\StableDiffusion\web-ui\extensions\stable-diffusion-webui-tensorrt\scripts\trt.py", line 6, in <module>
    from modules import script_callbacks, sd_unet, devices, shared, paths_internal
ImportError: cannot import name 'sd_unet' from 'modules' (unknown location)

Proof on dev branch:
> PS E:\StableDiffusion\web-ui> git checkout dev
Already on 'dev'
Your branch is up to date with 'origin/dev'

**Comment by papuSpartan** [comment]
Did you guys fetch the latest changes to dev with git fetch --all (or equivalent)?

**Comment by Xility-Wil** [comment]
> Did you guys fetch the latest changes to dev with git fetch --all (or equivalent)?

I can confirm about an hour after I originally posted, I realized I forgot to pull the new branch 🤦‍♂️

**Comment by dathide** [comment]
Still happening to me, even though the dev branch was merged 5 hours ago

**Comment by 4lt3r3go** [comment]
i did all and still get 
Error loading script: trt.py

**Comment by CyberTimon** [comment]
`(base) cybertimon@server:~/Repositories/stable-diffusion-webui/extensions/stable-diffusion-webui-tensorrt$ git checkout dev
error: pathspec 'dev' did not match any file(s) known to git`

I get this error everytime I try to checkout to dev branch. Any help?
