### ISSUE TITLE
Module onnx is not installed!

### ISSUE THREAD

**Issue by mattieshadow** [AUTOMATIC1111/stable-diffusion-webui-tensorrt#17]
```
============= Diagnostic Run torch.onnx.export version 2.0.0+cu118 =============
verbose: False, log level: Level.ERROR
======================= 0 NONE 0 NOTE 0 WARNING 0 ERROR ========================

Error completing request
Arguments: ('', 17) {}
Traceback (most recent call last):
  File "B:\AiGen\stable-diffusion-webui\venv\lib\site-packages\torch\onnx\_internal\onnx_proto_utils.py", line 219, in _add_onnxscript_fn
    import onnx
  File "B:\AiGen\stable-diffusion-webui\venv\lib\site-packages\onnx\__init__.py", line 7, in <module>
    from onnx.external_data_helper import (
  File "B:\AiGen\stable-diffusion-webui\venv\lib\site-packages\onnx\external_data_helper.py", line 9, in <module>
    from .onnx_pb import AttributeProto, GraphProto, ModelProto, TensorProto
  File "B:\AiGen\stable-diffusion-webui\venv\lib\site-packages\onnx\onnx_pb.py", line 4, in <module>
    from .onnx_ml_pb2 import *  # noqa
  File "B:\AiGen\stable-diffusion-webui\venv\lib\site-packages\onnx\onnx_ml_pb2.py", line 5, in <module>
    from google.protobuf.internal import builder as _builder
ImportError: cannot import name 'builder' from 'google.protobuf.internal' (B:\AiGen\stable-diffusion-webui\venv\lib\site-packages\google\protobuf\internal\__init__.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "B:\AiGen\stable-diffusion-webui\modules\call_queue.py", line 57, in f
    res = list(func(*args, **kwargs))
  File "B:\AiGen\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "B:\AiGen\stable-diffusion-webui\extensions\stable-diffusion-webui-tensorrt\ui_trt.py", line 21, in export_unet_to_onnx
    export_onnx.export_current_unet_to_onnx(filename, opset)
  File "B:\AiGen\stable-diffusion-webui\extensions\stable-diffusion-webui-tensorrt\export_onnx.py", line 27, in export_current_unet_to_onnx
    torch.onnx.export(
  File "B:\AiGen\stable-diffusion-webui\venv\lib\site-packages\torch\onnx\utils.py", line 506, in export
    _export(
  File "B:\AiGen\stable-diffusion-webui\venv\lib\site-packages\torch\onnx\utils.py", line 1620, in _export
    proto = onnx_proto_utils._add_onnxscript_fn(
  File "B:\AiGen\stable-diffusion-webui\venv\lib\site-packages\torch\onnx\_internal\onnx_proto_utils.py", line 221, in _add_onnxscript_fn
    raise errors.OnnxExporterError("Module onnx is not installed!") from e
torch.onnx.errors.OnnxExporterError: Module onnx is not installed!
```

I get the following error after attempting to convert Unet to ONNX in the webui. It takes roughly 1 minute, before getting this error.
Running a founders 3080 (10GB vram), although I don't think that makes a difference. Attempted to install onnx, but it didn't get installed in the venv, so I tried to install it in the venv and that that didn't seem to want to work. Any assistance?

**Comment by yoinked-h** [comment]
oh yeah protobuf has some issue with latest
