### ISSUE TITLE
Can't find TensorRT Directory?

### ISSUE THREAD

**Issue by briwil** [AUTOMATIC1111/stable-diffusion-webui-tensorrt#21]
I keep getting this, even though (see attachment) I have the Tensor directory where it should be-

Error running install.py for extension C:\SD\extensions\stable-diffusion-webui-tensorrt.
Command: "C:\SD\venv\Scripts\python.exe" "C:\SD\extensions\stable-diffusion-webui-tensorrt\install.py"
Error code: 1
stdout: Could not find TensorRT directory; skipping install Was not able to find TensorRT directory. Looked in: C:\SD\extensions\stable-diffusion-webui-tensorrt\.git, C:\SD\extensions\stable-diffusion-webui-tensorrt\scripts, C:\SD\extensions\stable-diffusion-webui-tensorrt\__pycache__

stderr: Traceback (most recent call last):
  File "C:\SD\extensions\stable-diffusion-webui-tensorrt\install.py", line 29, in <module>
    if trt_paths:
NameError: name 'trt_paths' is not defined

![Screenshot 2023-05-29 203128](https://github.com/AUTOMATIC1111/stable-diffusion-webui-tensorrt/assets/229978/f000ad11-ecd8-468f-a154-88a12fec43fa)

**Comment by jilek-josef** [comment]
Put it to same level as scripts

**Comment by briwil** [comment]
Did that, still getting the same results. Also reinstalled 1111 but same results.

`stdout: Could not find TensorRT directory; skipping install Was not able to find TensorRT directory. Looked in: C:\SD2\extensions\stable-diffusion-webui-tensorrt\.git, C:\SD2\extensions\stable-diffusion-webui-tensorrt\scripts, C:\SD2\extensions\stable-diffusion-webui-tensorrt\stable-diffusion-webui-tensorrt, C:\SD2\extensions\stable-diffusion-webui-tensorrt\__pycache__`

**Comment by DuckersMcQuack** [comment]
Got these today as well.

stderr: Traceback (most recent call last):
  File "H:\Stablediff\Automatic1111\WebuiDuckers\webui\extensions\stable-diffusion-webui-tensorrt\install.py", line 29, in <module>
    if trt_paths:
NameError: name 'trt_paths' is not defined

Error loading script: trt.py
Traceback (most recent call last):
  File "H:\Stablediff\Automatic1111\WebuiDuckers\webui\modules\scripts.py", line 263, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "H:\Stablediff\Automatic1111\WebuiDuckers\webui\modules\script_loading.py", line 10, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "H:\Stablediff\Automatic1111\WebuiDuckers\webui\extensions\stable-diffusion-webui-tensorrt\scripts\trt.py", line 6, in <module>
    from modules import script_callbacks, sd_unet, devices, shared, paths_internal
ImportError: cannot import name 'sd_unet' from 'modules' (unknown location)

**Comment by Booblerider** [comment]
Same problem here. Anyone have any solutions?

**Comment by lzplzp001** [comment]
我也遇到这一个问题，最后我在脚本目录的readme中找到了问题，安装TensorRT，需要从从[NVIDIA]下载带有TensorRT的zip.
并且与操作系统及CUDA版本一致。然后解压到脚本所在的目录。

原文如下：
Apart from installing the extension normally, you also need to download zip with TensorRT from [NVIDIA](https://developer.nvidia.com/nvidia-tensorrt-8x-download).
You need to choose the same version of CUDA as python's torch library is using. For torch 2.0.1 it is CUDA 11.8.
Extract the zip into extension directory, so that `TensorRT-8.6.1.6` (or similarly named dir) exists in the same place as `scripts` directory and `trt_path.py` file. Restart webui afterwards.
You don't need to install CUDA separately.

百度翻译：
除了正常安装扩展外，您还需要从[NVIDIA]下载带有TensorRT的zip(https://developer.nvidia.com/nvidia-tensorrt-8x-download)。
您需要选择与python的torch库使用的CUDA版本相同的CUDA。对于火炬2.0.1，它是CUDA 11.8。
将zip解压缩到扩展目录中，使“TensorRT-8.6.1.6”（或类似名称的dir）与“scripts”目录和“trt_path.py”文件位于同一位置。之后重新启动webui。

**Comment by Xav-Pe** [comment]
Same error.

```
*** Error loading script: trt.py
    Traceback (most recent call last):
      File "C:\Users\USER\stable-diffusion-webui\modules\scripts.py", line 527, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\Users\USER\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\Users\USER\stable-diffusion-webui\extensions\stable-diffusion-webui-tensorrt\scripts\trt.py", line 8, in <module>
        import trt_paths
      File "C:\Users\USER\stable-diffusion-webui\extensions\stable-diffusion-webui-tensorrt\trt_paths.py", line 47, in <module>
        set_paths()
      File "C:\Users\USER\stable-diffusion-webui\extensions\stable-diffusion-webui-tensorrt\trt_paths.py", line 30, in set_paths
        assert trt_path is not None, "Was not able to find TensorRT directory. Looked in: " + ", ".join(looked_in)
    AssertionError: Was not able to find TensorRT directory. Looked in: C:\Users\USER\stable-diffusion-webui\extensions\stable-diffusion-webui-tensorrt\.git, C:\Users\USER\stable-diffusion-webui\extensions\stable-diffusion-webui-tensorrt\scripts, C:\Users\USER\stable-diffusion-webui\extensions\stable-diffusion-webui-tensorrt\__pycache__
```

![image](https://github.com/AUTOMATIC1111/stable-diffusion-webui-tensorrt/assets/40688444/317ced8e-8461-414f-8f1c-43c3395f2508)
