### ISSUE TITLE
"System cannot find path specified" when trying to convert to onnx

### ISSUE THREAD

**Issue by DuckersMcQuack** [AUTOMATIC1111/stable-diffusion-webui-tensorrt#42]
windows on C, automatic on H.

Applying attention optimization: xformers... done.
Disabling attention optimization
*** Error completing request
*** Arguments: ('perfectdeliberate_tensorRT', 17) {}
    Traceback (most recent call last):
      File "H:\Stablediff\Automatic1111\Automatic1111 webui\webui\modules\call_queue.py", line 55, in f
        res = list(func(*args, **kwargs))
      File "H:\Stablediff\Automatic1111\Automatic1111 webui\webui\modules\call_queue.py", line 35, in f
        res = func(*args, **kwargs)
      File "H:\Stablediff\Automatic1111\Automatic1111 webui\webui\extensions\stable-diffusion-webui-tensorrt\ui_trt.py", line 21, in export_unet_to_onnx
        export_onnx.export_current_unet_to_onnx(filename, opset)
      File "H:\Stablediff\Automatic1111\Automatic1111 webui\webui\extensions\stable-diffusion-webui-tensorrt\export_onnx.py", line 24, in export_current_unet_to_onnx
        os.makedirs(os.path.dirname(filename), exist_ok=True)
      File "C:\Users\Duckers\AppData\Local\Programs\Python\Python310\lib\os.py", line 225, in makedirs
        mkdir(name, mode)
    FileNotFoundError: [WinError 3] The system cannot find the path specified: ''

**Comment by Z0rx** [comment]
same here

**Comment by CaptainDoubleYou** [comment]
I had to type it manually:
W:\AI\stable-diffusion-webui\models\Unet-onnx\animesh_PrunedV21.onnx

Just do that and it will work. (You need to specify where the file is and the full extension as well.)
