### ISSUE TITLE
RuntimeError: Expected all tensors to be on the same device

### ISSUE THREAD

**Issue by jilek-josef** [AUTOMATIC1111/stable-diffusion-webui-tensorrt#8]
Hmm, what to do?
Applying attention optimization: sdp... done.
Weights loaded in 10.6s (calculate hash: 4.9s, load weights from disk: 0.2s, apply weights to model: 4.7s, load VAE: 0.7s).
Disabling attention optimization
============= Diagnostic Run torch.onnx.export version 2.0.0+cu118 =============
verbose: False, log level: Level.ERROR
======================= 0 NONE 0 NOTE 0 WARNING 0 ERROR ========================

Error completing request
Arguments: ('', 17) {}
Traceback (most recent call last):
  File "C:\Users\jilek\Documents\stable-diffusion-webui\modules\call_queue.py", line 57, in f
    res = list(func(*args, **kwargs))
  File "C:\Users\jilek\Documents\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "C:\Users\jilek\Documents\stable-diffusion-webui\extensions\stable-diffusion-webui-tensorrt\ui_trt.py", line 21, in export_unet_to_onnx
    export_onnx.export_current_unet_to_onnx(filename, opset)
  File "C:\Users\jilek\Documents\stable-diffusion-webui\extensions\stable-diffusion-webui-tensorrt\export_onnx.py", line 27, in export_current_unet_to_onnx
    torch.onnx.export(
  File "C:\Users\jilek\Documents\stable-diffusion-webui\venv\lib\site-packages\torch\onnx\utils.py", line 506, in export
    _export(
  File "C:\Users\jilek\Documents\stable-diffusion-webui\venv\lib\site-packages\torch\onnx\utils.py", line 1548, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "C:\Users\jilek\Documents\stable-diffusion-webui\venv\lib\site-packages\torch\onnx\utils.py", line 1113, in _model_to_graph
    graph, params, torch_out, module = _create_jit_graph(model, args)
  File "C:\Users\jilek\Documents\stable-diffusion-webui\venv\lib\site-packages\torch\onnx\utils.py", line 989, in _create_jit_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args)
  File "C:\Users\jilek\Documents\stable-diffusion-webui\venv\lib\site-packages\torch\onnx\utils.py", line 893, in _trace_and_get_graph_from_model
    trace_graph, torch_out, inputs_states = torch.jit._get_trace_graph(
  File "C:\Users\jilek\Documents\stable-diffusion-webui\venv\lib\site-packages\torch\jit\_trace.py", line 1268, in _get_trace_graph
    outs = ONNXTracedModule(f, strict, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "C:\Users\jilek\Documents\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\jilek\Documents\stable-diffusion-webui\venv\lib\site-packages\torch\jit\_trace.py", line 127, in forward
    graph, out = torch._C._create_graph_by_tracing(
  File "C:\Users\jilek\Documents\stable-diffusion-webui\venv\lib\site-packages\torch\jit\_trace.py", line 118, in wrapper
    outs.append(self.inner(*trace_inputs))
  File "C:\Users\jilek\Documents\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\jilek\Documents\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1488, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "C:\Users\jilek\Documents\stable-diffusion-webui\modules\sd_unet.py", line 91, in UNetModel_forward
    return ldm.modules.diffusionmodules.openaimodel.copy_of_UNetModel_forward_for_webui(self, x, timesteps, context, *args, **kwargs)
  File "C:\Users\jilek\Documents\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\openaimodel.py", line 789, in forward
    emb = self.time_embed(t_emb)
  File "C:\Users\jilek\Documents\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\jilek\Documents\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1488, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "C:\Users\jilek\Documents\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\container.py", line 217, in forward
    input = module(input)
  File "C:\Users\jilek\Documents\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\jilek\Documents\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1488, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "C:\Users\jilek\Documents\stable-diffusion-webui\extensions-builtin\Lora\lora.py", line 400, in lora_Linear_forward
    return torch.nn.Linear_forward_before_lora(self, input)
  File "C:\Users\jilek\Documents\stable-diffusion-webui\extensions\a1111-sd-webui-lycoris\lycoris.py", line 734, in lyco_Linear_forward
    return torch.nn.Linear_forward_before_lyco(self, input)
  File "C:\Users\jilek\Documents\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument mat1 in method wrapper_CUDA_addmm)

**Comment by merc4derp** [comment]
Check your cmdline parameters. Get rid of medvram/lowvram.

**Comment by jilek-josef** [comment]
Yes, it was medvram, thanks

**Comment by Debodeep94** [comment]
how did you solve with the medvram? Can you explain a bit, please?
